name: Rust

on:
  push:
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests under valgrind
      run: cargo test --no-run && valgrind --leak-check=full --show-leak-kinds=all --error-exitcode=1 -v --suppressions=valgrind.supp  $(find target/debug/deps -regextype sed -regex ".*/blop[^.]*")
